# Generated by Django 3.0.3 on 2020-04-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='Enter blogger nickname', max_length=50)),
                ('bio', models.CharField(help_text='Enter blogger biographical information', max_length=300)),
            ],
            options={
                'ordering': ['nickname'],
            },
        ),
    ]
