# Generated by Django 3.0.3 on 2020-04-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, help_text='Enter post text'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
