# Generated by Django 3.0.3 on 2020-04-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200418_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Enter post text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(null=True),
        ),
    ]
