# Generated by Django 3.0.7 on 2020-07-23 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200707_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 23, 9, 40, 19, 777635), verbose_name='Post date'),
        ),
    ]
