# Generated by Django 3.0.7 on 2020-09-01 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200723_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(default=datetime.date(2020, 9, 1), verbose_name='Post date'),
        ),
    ]
